language: python
python:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
#  - 3.2
#  - 3.3
env:
#  - DJANGO=1.1.4
#  - DJANGO=1.2.7
#  - DJANGO=1.3.7
  - DJANGO=1.4.10
#  - DJANGO=1.5.5
install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install python-memcached --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=johnny manage.py test --traceback
after_success:
  - coveralls

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.10
    - python: 3.3
      env: DJANGO=1.4.10
