language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
services:
  - memcached
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.10
  - DJANGO=1.5.5
install:
  - pip install Django==$DJANGO coveralls --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]
       || [[ $TRAVIS_PYTHON_VERSION == 3.3 ]];
    then
      pip install python3-memcached --use-mirrors;
    else
      pip install python-memcached --use-mirrors;
    fi
script:
  - coverage run --source=johnny manage.py test --traceback
after_success:
  - coveralls

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.3.7
    - python: 3.3
      env: DJANGO=1.3.7
    - python: 3.2
      env: DJANGO=1.4.10
    - python: 3.3
      env: DJANGO=1.4.10
